Repository Brend-VanDenEynde/Programming-Project-2025-Groep-1, pull requests merged in 2025-06, with the labels that each got.

#45 Enhance student and bedrijf profile avatar functionality and layout
  career-launch/src/css/consolidated-style.css
  career-launch/src/pages/bedrijf/bedrijf-profiel.js
  career-launch/src/pages/student/student-profiel.js
Labels: enhancement

#68 Refactor user data handling to eliminate localStorage usage
  career-launch/src/pages/register-bedrijf/bedrijf-register.js
  career-launch/src/pages/register-student/student-opleiding.js
  career-launch/src/pages/register-student/student-register.js
  career-launch/src/pages/register.js
Labels: enhancement

#81 Add sector ID fetching and error handling in bedrijf profiel
  career-launch/src/pages/bedrijf/bedrijf-profiel.js
Labels: enhancement

#85 Refactor API calls for improved authentication handling
  career-launch/src/pages/admin/admin-bedrijven-in-behandeling.js
  career-launch/src/pages/admin/admin-company-detail.js
  career-launch/src/pages/admin/admin-ingeschreven-bedrijven.js
  career-launch/src/pages/admin/admin-processing-company-detail.js
  career-launch/src/pages/admin/admin-student-detail.js
  career-launch/src/pages/admin/admin.js
  career-launch/src/pages/bedrijf/bedrijf-profiel.js
  career-launch/src/pages/bedrijf/bedrijf-speeddates-verzoeken.js
  career-launch/src/pages/bedrijf/bedrijf-speeddates.js
  career-launch/src/pages/bedrijf/search-criteria-bedrijf.js
  career-launch/src/pages/bedrijf/studenten.js
  career-launch/src/pages/login.js
  career-launch/src/pages/register-bedrijf/bedrijf-register.js
  career-launch/src/pages/register-student/student-opleiding.js
  career-launch/src/pages/register-student/student-register.js
  career-launch/src/pages/student/bedrijven.js
  career-launch/src/pages/student/search-criteria-student.js
  career-launch/src/pages/student/student-profiel.js
  career-launch/src/pages/student/student-skills.js
  career-launch/src/pages/student/student-speeddates-verzoeken.js
  career-launch/src/pages/student/student-speeddates.js
  career-launch/src/utils/api.js
  career-launch/src/utils/auth-api.js
  career-launch/src/utils/data-api.js
  career-launch/src/utils/fetch-student-profile.js
  career-launch/src/utils/registration-api.js
Labels: enhancement, fixed it

#86 Update alert messages for account creation to formal language
  career-launch/src/pages/login.js
  career-launch/src/pages/register-bedrijf/bedrijf-register.js
Labels: enhancement, fixed it

#90 Enhance Content-Type header handling for JSON bodies in authenticatedFetch
  career-launch/src/utils/auth-api.js
Labels: fixed it

#91 feat(search-ui): Enhance search field styling and interactivity
  career-launch/src/css/consolidated-style.css
  career-launch/src/pages/student/student-profiel.js
Labels: enhancement

#92 Add upload icon text and improve visibility handling for uploaded photos
  career-launch/src/css/consolidated-style.css
  career-launch/src/pages/register-bedrijf/bedrijf-register.js
  career-launch/src/pages/register-student/student-register.js
Labels: fixed it

#96 style(homepage): restore centered layout and refine button styles
  career-launch/src/css/consolidated-style.css
Labels: enhancement

#105 Enhance README for clarity and completeness
  README.md
Labels: documentation

#112 feat(ui): Remove match percentage legend
  career-launch/src/pages/bedrijf/studenten.js
Labels: enhancement

#113 Update fallback image URL for company logos
  career-launch/src/pages/student/bedrijven.js
Labels: enhancement

#122 Fix time formatting in showBedrijfPopup function
  career-launch/src/pages/student/bedrijven.js
Labels: fixed it

#126 Refactor logout functionality and improve user session management
  career-launch/src/pages/admin/admin-bedrijven-in-behandeling.js
  career-launch/src/pages/admin/admin-company-detail.js
  career-launch/src/pages/admin/admin-contact-detail.js
  career-launch/src/pages/admin/admin-contacten.js
  career-launch/src/pages/admin/admin-ingeschreven-bedrijven.js
  career-launch/src/pages/admin/admin-ingeschreven-studenten.js
  career-launch/src/pages/admin/admin-processing-company-detail.js
  career-launch/src/pages/admin/admin-settings.js
  career-launch/src/pages/bedrijf/bedrijf-profiel.js
  career-launch/src/pages/bedrijf/bedrijf-settings.js
  career-launch/src/pages/bedrijf/bedrijf-speeddates-verzoeken.js
  career-launch/src/pages/bedrijf/bedrijf-speeddates.js
  career-launch/src/pages/bedrijf/search-criteria-bedrijf.js
  career-launch/src/pages/bedrijf/studenten.js
  career-launch/src/pages/student/bedrijven.js
  career-launch/src/pages/student/search-criteria-student.js
  career-launch/src/pages/student/student-profiel.js
  career-launch/src/pages/student/student-settings.js
  career-launch/src/pages/student/student-speeddates-verzoeken.js
  career-launch/src/pages/student/student-speeddates.js
  career-launch/src/utils/auth-api.js
  career-launch/src/utils/bedrijf-navbar.js
Labels: enhancement, fixed it

#131 Add datepicker and dynamic time slot generation for speed dates
  career-launch/src/pages/bedrijf/studenten.js
  career-launch/src/pages/student/bedrijven.js
Labels: enhancement

#136 Add loading indicator and disable save button in profiles
  src/css/consolidated-style.css
  src/pages/bedrijf/bedrijf-profiel.js
  src/pages/student/student-profiel.js
Labels: enhancement
